apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t0vc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-t0vc@sha256:d63292008e77058f8a084fe69236321b31eadf146b5f7eff7c11f1b98f1d0f18
        name: my-nodejs
        resources: {}
status: {}
